audio:
  device_preferred: "BlackHole 2ch"
  sample_rate: 48000
  channels: 2
  autosave_sec: 10

asr:
  model: "small"
  language: "en"
  word_timestamps: false
  chunk_seconds: 30
  chunk_overlap_seconds: 3
  beam_size: 1

embeddings:
  model: "all-MiniLM-L6-v2"
  dim: 384

llm:
  provider: "lmstudio"
  base_url: "http://localhost:1234/v1"
  model: "llama-3.1-8b-instruct"
  temperature: 0.2
  max_tokens: 1200

rag:
  top_k: 6
  overlap_ratio: 0.1
  target_tokens: 1400
  sim_threshold: 0.8

storage:
  keep_audio: false
  format: "jsonl"
